"use client"

import Link from "next/link"
import Image from "next/image"
import { BrainCircuit } from "lucide-react"
import type { ClientReport } from "@/lib/lms-program-report"
import { clientSafeFeedback } from "@/lib/lms-report-shared"
import {
  Page, PageHeader, PageFooter, Metric, FeedbackBlock, SECTION, METRIC_NOTE, PRINT_CSS, SCREEN_PRINT_CSS,
  sc, fmtPct, fmtDay,
} from "@/components/lms/reports/ReportChrome"
import type { Audience } from "@/components/lms/reports/ProgramReportView"
import ExpertSummaryBody from "@/components/lms/reports/ExpertSummaryBody"
import { GroupedBars, ScoreBandsChart, CHART_COLORS, SCORE_BANDS } from "@/components/lms/reports/ReportCharts"

const STATUS: Record<string, string> = { active: "Running", completed: "Completed", archived: "Archived", draft: "Draft" }

// Client report (RL-7): every program delivered to one company.
export default function ClientReportView({ data, audience = "internal", includeComments = false, includeInternal = false, assessment = null, forPrint = false, linkMode = "admin" }: {
  data: ClientReport; audience?: Audience; includeComments?: boolean; includeInternal?: boolean
  assessment?: any | null; forPrint?: boolean
  linkMode?: "admin" | "viewer" | "none"
}) {
  const { company, totals, programs } = data
  const client = audience === "client"
  const hasExpert = (!client || includeInternal) && !!assessment?.executive_summary
  const mode = forPrint ? "none" : linkMode
  const links = mode !== "none"
  const programHref = (id: string) => mode === "viewer" ? `/viewer/lms/program/${id}` : `/lms-admin/reports/programs/${id}`
  const today = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })
  const logo = company.logo_url
  const courseFb = client ? clientSafeFeedback(data.feedback, includeComments) : { ...data.feedback, suppressed: false }
  const surveyFb = client ? clientSafeFeedback(data.survey, includeComments) : { ...data.survey, suppressed: false }
  const hasFeedback = data.feedback.responses > 0 || data.survey.responses > 0
  const hasCompare = programs.length > 1
  const order = ["cover", "overview", ...(hasCompare ? ["compare"] : []), ...(hasFeedback ? ["feedback"] : []), ...(hasExpert ? ["expert"] : []), "programs"]
  const pageNo = (k: string) => order.indexOf(k) + 1
  const total = order.length

  return (
    <>
      <style>{forPrint ? PRINT_CSS : SCREEN_PRINT_CSS}</style>
      <div id="report-root" className="flex flex-col" style={forPrint ? { width: 794 } : { width: 794, margin: "0 auto", boxShadow: "0 0 0 1px #e2e8f0", background: "white" }}>

        <Page dark first>
          <div className="flex items-center justify-between px-12 pt-10 shrink-0">
            <Image src="/logo/logo-white.png" alt="ICS Aviation" width={130} height={36} className="object-contain" />
            <p className="text-white/40 text-xs">{today}</p>
          </div>
          <div className="flex-1 flex flex-col items-center justify-center px-12 text-center gap-7">
            {logo && (
              <div className="bg-white rounded-2xl px-6 py-4">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src={logo} alt={company.name} className="h-14 max-w-[220px] object-contain" />
              </div>
            )}
            <p className="text-white/50 text-[11px] uppercase tracking-[0.4em]">Client Training Report</p>
            <div>
              <h1 className="text-4xl font-extrabold text-white tracking-tight">{company.name}</h1>
              <p className="text-white/50 text-sm mt-2">{[company.code, company.sector, company.country].filter(Boolean).join(" · ")}</p>
            </div>
            <div className="grid grid-cols-4 gap-6">
              {[["Programs", String(totals.programs)], ["Trained", String(totals.trained)], ["Pass rate", fmtPct(totals.passRate)], ["Certificates", String(totals.certificates)]].map(([l, v]) => (
                <div key={l} className="text-center"><p className="text-2xl font-bold text-white">{v}</p><p className="text-white/40 text-[10px] uppercase tracking-widest mt-1">{l}</p></div>
              ))}
            </div>
          </div>
          <div className="px-12 py-6 border-t border-white/10 flex items-center justify-between shrink-0">
            <div className="flex items-center gap-2"><BrainCircuit className="h-3.5 w-3.5 text-purple-300/60" /><p className="text-white/30 text-[10px]">Generated by ICS Expert Analytics</p></div>
            <p className="text-white/20 text-[9px]">Page 1 of {total}</p>
          </div>
        </Page>

        <Page>
          <PageHeader title="Overview" subtitle={company.name} today={today} logoUrl={logo} />
          <div className="px-12 py-7 space-y-6">
            <div className="avoid-break">
              <p className={`${SECTION} mb-3`}>Programs</p>
              <div className="grid grid-cols-4 gap-3">
                <Metric label="Delivered" value={String(totals.programs)} />
                <Metric label="Running" value={String(totals.activePrograms)} />
                <Metric label="Completed" value={String(totals.completedPrograms)} />
                <Metric label="People trained" value={String(totals.trained)} sub={`${totals.enrollments} course enrollments`} />
              </div>
            </div>
            <div className="avoid-break">
              <p className={`${SECTION} mb-3`}>Results</p>
              <div className="grid grid-cols-4 gap-3">
                <Metric label="Completion rate" value={fmtPct(totals.completionRate)} color={sc(totals.completionRate).t} />
                <Metric label="Pass rate" value={fmtPct(totals.passRate)} sub={totals.sat ? `${totals.passed}/${totals.sat} who sat the exam` : "nobody sat an exam yet"} color={sc(totals.passRate).t} />
                <Metric label="Average score" value={fmtPct(totals.avgScore)} color={sc(totals.avgScore).t} />
                <Metric label="Certificates" value={String(totals.certificates)} />
              </div>
            </div>
            {(data.scoreBands ?? []).some(n => n > 0) && (
              <div className="avoid-break">
                <p className={`${SECTION} mb-2`}>Final exam scores <span className="normal-case tracking-normal font-normal text-slate-400">· best attempt, all programs</span></p>
                <ScoreBandsChart bands={data.scoreBands} labels={SCORE_BANDS} height={150} />
              </div>
            )}
            {hasExpert && (
              <div className="avoid-break bg-[#1B4F8A]/5 border border-[#1B4F8A]/10 rounded-xl p-5">
                <p className="text-[10px] font-bold uppercase tracking-widest text-[#1B4F8A] mb-2">Expert Executive Summary</p>
                <p className="text-sm text-slate-700 leading-relaxed">{assessment.executive_summary}</p>
              </div>
            )}
            <p className="text-[10px] text-slate-400">{METRIC_NOTE}</p>
          </div>
          <PageFooter page={pageNo("overview")} total={total} confidential={!client} />
        </Page>

        {hasCompare && (
          <Page>
            <PageHeader title="Programs Over Time" subtitle={company.name} today={today} logoUrl={logo} />
            <div className="px-12 py-7 space-y-5">
              <p className="text-xs text-slate-500">Oldest first, so the trend across engagements reads top to bottom.</p>
              <GroupedBars
                series={[{ name: "Completion", color: CHART_COLORS.brand }, { name: "Pass rate", color: CHART_COLORS.teal }, { name: "Average score", color: CHART_COLORS.amber }]}
                rows={[...programs].sort((a, b) => (a.start_date ?? "").localeCompare(b.start_date ?? "")).map(p => ({
                  label: `${p.name}${p.start_date ? ` · ${new Date(p.start_date + "T00:00:00Z").toLocaleDateString("en-GB", { month: "short", year: "numeric", timeZone: "UTC" })}` : ""}`,
                  values: [p.completionRate, p.passRate, p.avgScore],
                }))}
              />
              <p className="text-[10px] text-slate-400">{METRIC_NOTE}</p>
            </div>
            <PageFooter page={pageNo("compare")} total={total} confidential={!client} />
          </Page>
        )}

        {hasFeedback && (
          <Page>
            <PageHeader title="Feedback" subtitle={company.name} today={today} logoUrl={logo} />
            <div className="px-12 py-7 space-y-8">
              <FeedbackBlock title="Course feedback (all programs)" summary={courseFb} suppressed={courseFb.suppressed} />
              {data.survey.responses > 0 && <FeedbackBlock title="End-of-program surveys" summary={surveyFb} suppressed={surveyFb.suppressed} />}
            </div>
            <PageFooter page={pageNo("feedback")} total={total} confidential={!client} />
          </Page>
        )}

        {hasExpert && (
          <Page>
            <PageHeader title="Expert Summary" subtitle={company.name} today={today} logoUrl={logo} />
            <ExpertSummaryBody assessment={assessment} />
            <PageFooter page={pageNo("expert")} total={total} confidential={!client} />
          </Page>
        )}

        <Page>
          <PageHeader title="Programs" subtitle={company.name} today={today} logoUrl={logo} />
          <div className="px-12 py-7 flex-1">
            {programs.length === 0 ? <p className="text-sm text-slate-400">No programs delivered yet.</p> : (
              <table className="w-full text-xs">
                <thead>
                  <tr className="border-b-2 border-slate-200 text-left text-slate-400 uppercase tracking-wider text-[9px]">
                    <th className="py-2 font-semibold">Program</th><th className="py-2 font-semibold">Students</th><th className="py-2 font-semibold">Completion</th>
                    <th className="py-2 font-semibold">Pass rate</th><th className="py-2 font-semibold">Avg score</th><th className="py-2 font-semibold">Certificates</th><th className="py-2 font-semibold">Rating</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {programs.map(p => (
                    <tr key={p.id} className="avoid-break">
                      <td className="py-2.5 pr-2">
                        {links ? <Link href={programHref(p.id)} className="font-medium text-slate-800 hover:text-[#1B4F8A] hover:underline">{p.name}</Link> : <span className="font-medium text-slate-800">{p.name}</span>}
                        <p className="text-[10px] text-slate-400">{[STATUS[p.status] ?? p.status, (p.start_date || p.end_date) && `${fmtDay(p.start_date)} → ${fmtDay(p.end_date)}`, p.reference].filter(Boolean).join(" · ")}</p>
                      </td>
                      <td className="py-2.5 text-slate-700">{p.students}</td>
                      <td className="py-2.5 text-slate-700">{fmtPct(p.completionRate)}</td>
                      <td className="py-2.5 font-medium" style={{ color: sc(p.passRate).t }}>{fmtPct(p.passRate)}</td>
                      <td className="py-2.5 font-medium" style={{ color: sc(p.avgScore).t }}>{fmtPct(p.avgScore)}</td>
                      <td className="py-2.5 text-slate-700">{p.certificates}</td>
                      <td className="py-2.5 text-slate-600">{p.feedbackAvg !== null && !client ? `${p.feedbackAvg.toFixed(1)}/5` : client && p.feedbackAvg !== null ? "see feedback" : "—"}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
          <PageFooter page={pageNo("programs")} total={total} confidential={!client} />
        </Page>
      </div>
    </>
  )
}
