/**
 * GET /lms/admin-preview-entry?token=RAW&to=/lms/courses/xxx
 *
 * Sets the student session cookie from the raw token generated by
 * /api/lms/admin/preview-as, then redirects to `to`.
 *
 * This lets an admin "become" a student in their browser to test
 * the student portal without needing the student's password.
 */
import { NextRequest, NextResponse } from "next/server"
import { cookies } from "next/headers"

const COOKIE_NAME  = "lms_session"
const SESSION_SECS = 2 * 60 * 60  // 2 hours

export async function GET(req: NextRequest) {
  const { searchParams } = req.nextUrl
  const token = searchParams.get("token")
  const to    = searchParams.get("to") ?? "/lms/dashboard"

  if (!token) {
    return NextResponse.redirect(new URL("/lms/login", req.url))
  }

  // Set the student cookie with the raw token
  const cookieStore = await cookies()
  cookieStore.set(COOKIE_NAME, token, {
    httpOnly: true,
    secure:   process.env.NODE_ENV === "production",
    sameSite: "lax",
    path:     "/",
    maxAge:   SESSION_SECS,
  })

  // Redirect to the student page
  const dest = to.startsWith("/") ? new URL(to, req.url) : new URL("/lms/dashboard", req.url)
  return NextResponse.redirect(dest)
}
